definitions:
  dto.ContainerByReceiptDTO:
    properties:
      containerID:
        type: integer
      receiptID:
        type: integer
      status:
        type: string
    type: object
  dto.CountDTO:
    properties:
      arrivedSoon:
        type: integer
      delay:
        type: integer
      onTheWay:
        type: integer
    type: object
  dto.ReceiptListByTypeResult:
    properties:
      content: { }
      pagination: { }
    type: object
  dto.ReceiptListResultDTO:
    properties:
      content: { }
      pagination: { }
    type: object
  dto.ReceiptNumber:
    properties:
      receiptSeaNumber:
        type: string
    type: object
  entity.Container:
    properties:
      id_container:
        type: integer
      id_rts:
        type: string
      kode:
        type: string
      nomor:
        type: string
      status:
        type: integer
      tanggal_arrived_c:
        type: string
      tanggal_berangkat_c:
        type: string
      tanggal_monitoring_c:
        type: string
      tgl_antri_kapal:
        type: string
      tgl_atur_kapal:
        type: string
      tgl_closing:
        type: string
      tgl_est_dumai:
        type: string
      tgl_eta:
        type: string
      tgl_loading:
        type: string
      tgl_notul:
        type: string
      tgl_pib:
        type: string
    type: object
  entity.Giw:
    properties:
      barang:
        type: string
      berat:
        type: string
      container:
        $ref: '#/definitions/entity.Container'
      container_id:
        type: integer
      ctns:
        type: integer
      harga:
        type: number
      harga_jual:
        type: number
      id:
        type: integer
      kurs:
        type: number
      nilai:
        type: string
      nomor:
        type: string
      note:
        type: string
      qty:
        type: integer
      remarks:
        type: string
      resi_id:
        type: integer
      volume:
        type: string
    type: object
  entity.Resi:
    properties:
      giw:
        items:
          $ref: '#/definitions/entity.Giw'
        type: array
      gudang:
        type: integer
      id_resi:
        type: integer
      id_resi_rts:
        type: integer
      konfirmasi_resi:
        type: string
      nomor:
        type: string
      supplier:
        type: string
      tanggal:
        type: string
      tel:
        type: string
    type: object
  helper.Response:
    properties:
      data: { }
      errors: { }
      message:
        type: string
      status:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /all:
    get:
      consumes:
      - application/json
      description: All Receipt Sea
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/helper.Response'
              - properties:
                  data:
                    items:
                      $ref: '#/definitions/entity.Resi'
                    type: array
                type: object
      summary: All example
  /container-by-receipt:
    post:
      consumes:
        - application/json
      description: Receipt By Container
      parameters:
        - description: ReceiptByContainer
          in: body
          name: ReceiptByContainer
          required: true
          schema:
            $ref: '#/definitions/dto.ReceiptNumber'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/helper.Response'
              - properties:
                  data:
                    $ref: '#/definitions/dto.ContainerByReceiptDTO'
                type: object
      summary: All example
  /count:
    get:
      consumes:
        - application/json
      description: Count Receipt Sea
      parameters:
        - description: 'Insert your access token. Format: Bearer access_token'
          in: header
          name: Authorization
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/helper.Response'
              - properties:
                  data:
                    $ref: '#/definitions/dto.CountDTO'
                type: object
      summary: All example
  /detail:
    get:
      consumes:
        - application/json
      description: Receipt Detail
      parameters:
        - description: ReceiptId
          in: query
          name: receiptId
          type: integer
        - description: ContainerId
          in: query
          name: containerId
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/helper.Response'
              - properties:
                  data:
                    $ref: '#/definitions/dto.ReceiptListResultDTO'
                type: object
      summary: All example
  /list:
    get:
      consumes:
        - application/json
      description: Receipt List
      parameters:
        - description: Pages
          in: query
          name: page
          type: integer
        - description: Limit
          in: query
          name: limit
          type: integer
        - description: Status
          in: query
          name: status
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/helper.Response'
              - properties:
                  data:
                    $ref: '#/definitions/dto.ReceiptListResultDTO'
                type: object
      summary: All example
  /receipt/list:
    get:
      consumes:
        - application/json
      description: Receipt List
      parameters:
        - description: Pages
          in: query
          name: page
          type: integer
        - description: Limit
          in: query
          name: limit
          type: integer
        - description: receiptType
          in: query
          name: receiptType
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/helper.Response'
              - properties:
                  data:
                    $ref: '#/definitions/dto.ReceiptListByTypeResult'
                type: object
      summary: All example
swagger: "2.0"
