definitions:
  helper.Pagination:
    properties:
      currentPage:
        type: integer
      limit:
        type: integer
      nextPage:
        type: integer
      order:
        type: string
      prevPage:
        type: integer
      sort:
        type: string
      totalElement:
        type: integer
      totalPage:
        type: integer
    type: object
  helper.PaginationResponse:
    properties:
      data: {}
      pagination:
        $ref: '#/definitions/helper.Pagination'
    type: object
info:
  contact: {}
paths:
  /transaction/report-merchant:
    get:
      consumes:
      - application/json
      description: Transaction Report By Merchant
      parameters:
      - description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.PaginationResponse'
      security:
      - BearerToken: []
      summary: Transaction Report By Merchant
  /transaction/report-outlet:
    get:
      consumes:
      - application/json
      description: Transaction Report By Outlet
      parameters:
      - description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.PaginationResponse'
      security:
      - BearerToken: []
      summary: Transaction Report By Outlet
swagger: "2.0"
