definitions:
  dto.ContainerByReceipt:
    properties:
      containerID:
        type: integer
      receiptID:
        type: integer
      status:
        type: string
    type: object
  dto.CountReceiptSea:
    properties:
      arrivedSoon:
        type: integer
      delay:
        type: integer
      onTheWay:
        type: integer
    type: object
  dto.ReceiptListByTypeResult:
    properties:
      content: { }
      pagination: { }
    type: object
  dto.ReceiptListResult:
    properties:
      content: { }
      pagination: { }
    type: object
  dto.ReceiptNumber:
    properties:
      receiptSeaNumber:
        type: string
    type: object
  helper.Response:
    properties:
      data: { }
      errors: { }
      message:
        type: string
      status:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /container-by-receipt:
    post:
      consumes:
        - application/json
      description: Receipt By Container
      parameters:
        - description: ReceiptByContainer
          in: body
          name: ReceiptByContainer
          required: true
          schema:
            $ref: '#/definitions/dto.ReceiptNumber'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/helper.Response'
              - properties:
                  data:
                    $ref: '#/definitions/dto.ContainerByReceipt'
                type: object
      summary: All example
  /count:
    get:
      consumes:
        - application/json
      description: Count Receipt Sea
      parameters:
        - description: 'Insert your access token. Format: Bearer access_token'
          in: header
          name: Authorization
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/helper.Response'
              - properties:
                  data:
                    $ref: '#/definitions/dto.CountReceiptSea'
                type: object
      summary: All example
  /detail:
    get:
      consumes:
        - application/json
      description: Receipt Detail
      parameters:
        - description: ReceiptId
          in: query
          name: receiptId
          type: integer
        - description: ContainerId
          in: query
          name: containerId
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/helper.Response'
              - properties:
                  data:
                    $ref: '#/definitions/dto.ReceiptListResult'
                type: object
      summary: All example
  /list:
    get:
      consumes:
        - application/json
      description: Receipt List
      parameters:
        - description: 'Insert your access token. Format: Bearer access_token'
          in: header
          name: Authorization
          required: true
          type: string
        - description: Pages
          in: query
          name: page
          type: integer
        - description: Limit
          in: query
          name: limit
          type: integer
        - description: Status
          in: query
          name: status
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/helper.Response'
              - properties:
                  data:
                    $ref: '#/definitions/dto.ReceiptListResult'
                type: object
      summary: All example
  /receipt/list:
    get:
      consumes:
        - application/json
      description: Receipt List
      parameters:
        - description: 'Insert your access token. Format: Bearer access_token'
          in: header
          name: Authorization
          required: true
          type: string
        - description: Pages
          in: query
          name: page
          type: integer
        - description: Limit
          in: query
          name: limit
          type: integer
        - description: receiptType
          in: query
          name: receiptType
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/helper.Response'
              - properties:
                  data:
                    $ref: '#/definitions/dto.ReceiptListByTypeResult'
                type: object
      summary: All example
swagger: "2.0"
