name: Publish Docker wilopo-cargo/service-receipt/service-receipt
on:
  push:
    branches:
      - develop
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Test Service Receipt Dockefile
        run: ls && cat Dockerfile
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: wilopo-cargo/service-receipt/service-receipt
          tag_with_ref: true
